### ISSUE TITLE
Single Cal causes PureSignal to toggle between automatic and manual [BUG]

### ISSUE THREAD

**Issue by w-u-2-o** [sjk7/Thetis-2.9.0#29] opened 2023-04-24 13:39 UTC
**Describe the bug**

On each operation of the Single Cal button PureSignal is toggled between automatic and manual mode.

While it is very good that sorely needed work has been done to improve PureSignal linearization ergonomics, the resulting logic, control and display behavior do not represent the intent or correct functionality of the PureSignal linearization subsystem.

**To Reproduce**

It is assumed the radio and software are configured for proper PureSignal operation.

Click PS-x button on main console until it shows PS-A (off).

Assert two tone test signal transmission.

Click single cal. PS state changes to PS-M (on). Indicators show "Feedback" (dimmed) and "Single Cal" (green).

Click single cal again. PS state changes to PS-A (on). Indicators show "Feedback" (green) and "Correcting" (green).

This pattern then repeats.

The programmed behavior is not desirable and does not meet the functional intent of how PureSignal linearization is supposed to work. Colorization of the single cal button is not desirable, again it does not represent a state.

**Expected behaviour**

The single cal button it intended to trigger a single calibration measurement only. I should not affect PureSignal mode of operation except to place PS into manual mode on the first, and only the first, actuation.

The following represents how PS did work and should work functionally. This is basically a return to how it operated in 2.9.0.8 but with improved and more logically arranged UI display behavior.

When PS is disabled:

Main console button should read "PS" and not be showing an ON state.
Feedback indicator should be dimmed.
PureSignal mode indicator should show "PureSignal2" dimmed.

When PS is in automatic mode:

Main console button should read "PS-A" and showing an ON state.
Feedback indicator should be indicating feedback levels as already designed.
PureSignal mode indicator should show "PureSignal2" or Correcting and dimmed or green as already designed.

When PS is in manual mode:

Main console button should read "PS-M" and showing an ON state.
Feedback indicator should be indicating "Single Cal" (this is a change, and is intended to reflect that continuous feedback is not being processed as it is in automatic mode).
PureSignal mode indicator should show "PureSignal2" or Correcting in the same manner as during automatic operation (this is a change, and is intended to notify the operator that during a transmission a PS correction is being applied as determined by the last manual single cal measurement).

Every time Single Cal is clicked:

The state of the main console PS button shall be changed to or maintained as PS-M and showing an ON state.
PS shall be commanded to make the single cal measurement and apply the results (no change).
The other PureSignal indicators shall operate as described above for PS manual mode.
Single cal. button shall not be colorized (it does not represent a state, only an action).

To leave PS manual mode:

The main console PS button is used to select either automatic or disabled modes.

**Desktop (please complete the following information):**

ANAN-8000DLE Protocol 2 FW 2.1.18, Thetis 2.9.0.19, Windows 10 Pro.

**Comment by sjk7** [comment] 2023-04-24 20:14
Whilst I agree with you that the single cal PS-M should display as correcting, I do not on its behaviour. It is as intended. The reason is that once you get a stable autocal, you may want to save it statically. This is why the button goes to PS-M immediately from PS-A. If you want to disable PS from here on in, you need to press it twice. 

Nobody wants to have to have the PS window open to effect single cal. Especially when auto-cal, as I have been hearing, sometimes freaks and causes a "picket fence 2 tone". That's bad enough, but I have heard it has also been destroying some solid state amps, with $200++ devices, sometimes x 2. So it is infinitely preferable to use manual puresignal over dynamic.

I will close this as I already have on the bug list that PS-M does not show as correcting. It is supposed to, and was coded that way, but something broke!

Thanks,
Steve

**Closed by sjk7** 2023-04-24 20:14 UTC
Labels: bug

**Comment by w-u-2-o** [comment] 2023-04-24 22:00
Sorry, Steve, I totally disagree with most of this.

Auto cal does not invoke two-tone. Nor does it ever cause "picket fence 2 tone", at least not on Apache hardware. If you are getting reports of this from Apache hardware users they are making some other mistake. I guarantee it. The picket fence issue has been resolved for a long time now. This is not to say it isn't happening on other hardware.

Further, auto cal is, in fact, preferable over manual. Almost no one uses manual except when they have some aberrant condition, or some special case like setting up to optimize linearity for digi mode operations.

If these were problems we'd be seeing many reports about this on the forum when we have none. I'd like to understand where you are getting these reports from. Again, this is not being reported by the Apache community. I know that you are HL2-centric (which is totally fine--no issue with that!) Is this a problem for the HL2 community? If so, then HL2 firmware or hardware changes might be necessary.

In auto cal no two tone is necessary. However, if two tone is used to set drive power or check linearity certain amp's will go into protection, most notably anything from Acom. The solution to that is to change the two tone freq's to 70 and 190Hz.

**Single cal is an action, not a state. If you pop a single cal by all means go into manual, but then stay there on subsequent single cal's, do not bounce back and forth between auto and manual.**

I will call this issue to the attention of Warren Pratt, the developer of PureSignal, in order to see if he would like to provide additional input. He is on vaca right now so he may not answer immediately.

Thanks,

Scott

**Comment by sjk7** [comment] 2023-04-25 02:28
Copied from other thread:
I should mention that PS-M is not the same as 'single' calibration in that PS-M inherits directly its settings from PS-A. This is why the button cycles PS-A -> PS->M -> no ps (off).

Assuming you have 'green' Pure Signal on PS-A, cycling the switch to PS-M remembers exactly the profile secured by PS-A. It does NOT do a single calibration here, it simply continues to use the 'green' PS-A setting.

**Comment by sjk7** [comment] 2023-04-25 02:42
@w-u-2-o 
But it _is_ a state now. It is the saved state of the last successful (green) dynamic puresignal settings. It is not the same as performing a single cal. I RTFM'd first and this is how I found you can ask PS for the state is _currently_has, and lock onto that. This is the reason why it cycles immed from PS-A to PS-M, so it can store it internally. Not saved in a file or anything, just keeping the last known good state.

It's not as good as PS-A in that it is a _static_ PS if you will, not a dynamic response so he can adjust to SWR changes, long-term changes in drive level and so on. If you don't want to sound like a Dalek at least once in an evening's QSO, this is what you have to do.

I have checked this on the spectrum analyzer and it really is OK and does keep the IMD low, until you change frequency/mode/band, when you have to go through it again. This way I can get low IMD on a net frequency and KNOW ps won't freak when it's my turn.

I have a friend with an ANAN-100, and he has (very rarely) seen the picket-fencing, though not nearly as frequently as I do , plus the thread I linked to also has a claim from another ham that it does indeed affect ANAN radios!

So, this is a before-not-coded Puresignal state, not a glorified single cal. You don't agree, but as a developer I sometimes have to make decisions, and this is one of those times. I don't see how we can get PS-M without having been in PS-A immediately beforehand (in order to freeze PS in this state), and that informed the design as a necessity more than. personal preference.

I could hide it behind yet another checkbox, but there are way too many options already to trip users up.

**Comment by sjk7** [comment] 2023-04-25 03:11
That said, I might have conflated Single cal with the new 'frozen' mode. I will look as I have to anyway as it is not displaying correctly. Having said that, I would like for threr to be some confirmation on the main window that single cal is in fact in effect.

That means in English that you should be able to perform singlecal as previously. And that should be for that transmission only, whereas the PS-M (which I could rename PS-F (frozen)) should stick. Eventually I may make it 'unstick' when changing mode/ power/ freq/ band. But I can already see the bug reports for that one:
 "PS-M" turns off when I change frequency, etc." LOL.

So watch the next release or the one after where I will fix the various bugs so that the only impact on 'don't care about frozen PS' just have to hit the PS button twice. That is the only _intended_ side effect here. Of course this means that the PS-M doesn't even need to be shown unless you are in TX, and have a good, current set of PS values.

Right, now I see why you think I don't understand how this all works, because currently SingleCal and PS-M are the same thing, but they are not really, these are just bugs from where I probably got disturbed half-way when applying the feature! But is still worth reading the prev reply of mine to see how I assert that that is _is_ a different and valid PS state from all the others we had before. A static state, but definitely a state.



Steve

**Comment by w-u-2-o** [comment] 2023-04-25 12:51
Steve,

Again my apologies for the annoying time zone difference that is
effectively delaying my replies. And I have a meeting this morning which
will further delay things. But I think we are getting very close to being
on the same page and I think I may have the answer for #16.

More to follow as soon as I can sit in front of a keyboard uninterrupted
for more than 5 minutes.

73!

Scott

**Comment by sjk7** [comment] 2023-04-25 13:34
No worries, Scott. Time is tight this week, so you may see some concise but hopefully not rude replies from me! :-)

Steve

**Comment by sjk7** [comment] 2023-04-27 22:33
I need to find a path of least resistance to make this work. I have started but not finished it, but I have removed the conflation between what I understand to be 'for this transmisson only' Single Cal vs 'get a good PS setting for this frequency, and hold it in place whilst PS-M is active.'

**Comment by w-u-2-o** [comment] 2023-04-28 00:29
Point of clarification: the single measurement and single correction that results from clicking the Single Cal button once is then maintained for all subsequent transmissions until PS is a) disabled, b) the correction is replaced by enabling PS-A, or c) the correction is replaced by another press of Single Cal.

That has been the behavior for many years up through and including 2.9.0.8.

The idea of PS-M is merely a special case of this.

In retrospect, IMHO, the best approach to this is as follows:

- Move the xPA button under DUP.
- Make a new button under PS-A called SCAL.
- HL2 users who think they need to use PS this way enabled PS-A, get the correction they want, press SCAL to lock it in.
- Alternately, they do it the way us Apache guys have been doing it, which is to transmit and bang away at the SCAL button until you get what you want, then just leave it alone.
- Illuminate/highlight the SCAL button to show it is active.
- Show "Correcting" during a TX if a valid SCAL correction is being utilized (that was definitely an omission that needed to be fixed).
