### ISSUE TITLE
[BUG] Waterfall display upon starting with AVG enabled

### ISSUE THREAD

**Issue by RdWing** [sjk7/Thetis-2.9.0#11] opened 2023-04-16 22:02 UTC
ANAN 7000 DLE Mk2.5 (EP4CE) P2 v2.1.2.27G
v2.9.0.15 x64 and previous
Win 11

Upon booting Thetis with AVG enabled, the Waterfall display appears blown out. Remediation is possible by cycling the AVG button off and back on, which restores expected operation.
![image](https://user-images.githubusercontent.com/19214916/232344963-32433ebc-6081-417b-9c23-4c1dc6519878.png)
![image](https://user-images.githubusercontent.com/19214916/232344985-5b213c1c-8c7b-43fd-ac7b-6f2a6827d602.png)
![image](https://user-images.githubusercontent.com/19214916/232345066-de59ae14-a059-4d76-a262-39331f095b48.png)

This problem does not occur with 2.9.0.8.

**Comment by sjk7** [comment] 2023-04-17 06:00
Ah, very good. I had seen the washed-out waterfall, and after I could not replicate. Assuming I can now, I will put it right.

Steve

**Comment by sjk7** [comment] 2023-04-18 01:50
Have definitely seen it, but cannot reproduce it now. Do you have a set of steps to reproduce it, please?

**Comment by RdWing** [comment] 2023-04-18 08:57
Fresh Reset DB.
Model to 7000 DLE
Setup -> Display -> RX1
-Enable Averaging
-Waterfall Averaging: Time Window
Restart Thetis
Power On

Already at this state you can see the Waterfall is not correct (All black/too dark). Toggle AVG off and back ON and it will restore normal operation.

Too see it blown out, enable Display -> RX1 -> Use Spec Min/Max and restart Thetis, you should see the problem as originally reported.

**Comment by sjk7** [comment] 2023-04-18 15:57
That's excellent feedback, thank you!

**Comment by sjk7** [comment] 2023-04-18 18:42
Note to self: When it does it for me, it is because the spec min and max have equal, invalid settings.

**Comment by RdWing** [comment] 2023-04-18 19:20
So on a fresh database, were you able to replicate? 
For me the spec min max, I didn't change after resetting the db. They are -140 dBm through -40 dBm.
![image](https://user-images.githubusercontent.com/19214916/232882791-94dd03b4-143a-4178-a3bb-77cf785b476c.png)

**Comment by RdWing** [comment] 2023-04-22 04:48
@sjk7 Did you get a chance to see if you could replicate?

**Comment by sjk7** [comment] 2023-04-26 04:04
> @sjk7 Did you get a chance to see if you could replicate?

Yes, without much success. Following your instructions carefully.

**Comment by RdWing** [comment] 2023-04-26 18:22
https://youtu.be/ECxBJyeucQs

Hope this helps, I made a short video showing how I can reproduce it on a fresh db.

**Comment by sjk7** [comment] 2023-04-27 12:49
All right, thanks.
Hopefully fixed in a later revison.

**Closed** 2023-04-27 12:50 UTC
Labels: bug, good first issue, Good Feedback
