### ISSUE TITLE
[BUG] In 2.9.0.23, RX1 seems to disconnect after transmit but can be reconnected by pushing TUN button.

### ISSUE THREAD

**Issue by oldjackbob** [sjk7/Thetis-2.9.0#38] opened 2023-04-28 12:41 UTC
After a phone transmission is initiated by PTT or MOX, when TX is ended the RX1 panafall behaves as though the antenna has been disconnected. There is no signal displayed anymore in the panafall and no audio coming from the speakers. Pressing and releasing the TUN button restores all signals to the panafall and speakers.

Prior to 2.9.0.23 Thetis has always run without any problems. After uninstalling 2.9.0.23 and reinstalling 2.9.0.21 the problem no longer exists.

OS: Windows 11 Beta, old i7-6700K.

Mark

_EDIT:_  After reading https://github.com/sjk7/Thetis-2.9.0/issues/39 I've determined that my https://github.com/sjk7/Thetis-2.9.0/issues/38 is related to the same bug, as I usually operate with "RX BYPASS on TX" enabled. However, if I disable "RX BYPASS on TX" then RX1 behaves as expected and https://github.com/sjk7/Thetis-2.9.0/issues/38 does not occur (of course I lose the ability to correct the IMD3 in my external amplifier).

**Comment by oldjackbob** [comment] 2023-04-28 12:53
Behavior is as noted in the title, it doesn't matter whether TX is initiated by PTT or MOX. When TX is ended there is no signal displayed on the panafall and no audio coming from the speakers. Pressing and releasing the TUN button will restore all signals to the panafall and speakers.

OS: Windows 11 Beta, old i7-6700K but normally runs Thetis without any problem.

**Comment by oldjackbob** [comment] 2023-04-28 23:17
After reading #39 I've determined that my #38 is related to the same bug, as I usually operate with "RX BYPASS on TX" enabled. However, if I disable "RX BYPASS on TX" then RX1 behaves as expected and #38 does not occur (of course I lose the ability to correct the IMD3 in my external amplifier).

Mark

**Comment by NC3Z** [comment] 2023-04-28 23:24
I can duplicate the issue here with my 7000DLE. If I have RX Bypass on TX checked, then after a PTT then RX1 will go dead. I either have to uncheck it and PTT again, or I can toggle between TX antenna and RX antenna to bring it back.

**Comment by torrenthd** [comment] 2023-04-29 05:22
Same problem here on my 7000DLE blue face.
Problem also appears after 2TON.

Reverted back to 2.9.0.21and no issues.

**Comment by sjk7** [comment] 2023-04-29 06:38
I am hunting around looking for this RX Bypass on TX, where is it hiding?

Steve

**Comment by torrenthd** [comment] 2023-04-29 06:42
GM Steve,

I don't understand you question...

73
Jordi
EA3CL

**Comment by sjk7** [comment] 2023-04-29 06:43
> If I have RX Bypass on TX checked

@torrenthd I am asking where this checkbox is
Steve

**Comment by torrenthd** [comment] 2023-04-29 06:45
Setup, general, Ant/filters

**Comment by sjk7** [comment] 2023-04-29 06:47
ah i saw it in the other thread, "in the "Ant/Filters" tab of the Setup"
Need. More. Coffee.

**Comment by sjk7** [comment] 2023-04-29 06:52
I'm finding some wierdness with the DUP button also. Depending on its position, I can lose RX even after retuning slightly!

**Comment by torrenthd** [comment] 2023-04-29 06:58
> I'm finding some wierdness with the DUP button also. Depending on its position, I can lose RX even after retuning slightly!

My DUP button is always ON

**Comment by sjk7** [comment] 2023-04-29 07:44
Can some kind soul post their database here, please?

**Comment by sjk7** [comment] 2023-04-29 08:34
All right guys, this one is tough. No ANAN hardware here, I could do with a repro for someone with a HL2. Without that, I am going to roll the code back to waypoints until we find this has gone away. So, please download the "latest", revision and let me know if the problem goes away. I updated it just now: 0934 UTC

Steve

**Comment by RdWing** [comment] 2023-04-29 08:47
[database.zip](https://github.com/sjk7/Thetis-2.9.0/files/11358725/database.zip)
Here's my R21 db that causes the issue when used on R23.
If there's anything I can do to help lmk.

**Comment by sjk7** [comment] 2023-04-29 08:53
> [database.zip](https://github.com/sjk7/Thetis-2.9.0/files/11358725/database.zip) Here's my R21 db that causes the issue when used on R23. If there's anything I can do to help lmk. RX Bypass on TX (checked) is used to instruct one of the relays in the 7000's to switch the RX Bypass port to the FPGA for PureSignal external feedback purposes. Unchecked the radio uses a built in sampler.

Thanks. How does the so-called rev 24 behave for you? Just uploaded. We will take steps back until the problem goes away.

**Comment by sjk7** [comment] 2023-04-29 09:07
@RdWing Hi is there any visual display on the setup form anywhere that this RX bypass on TX is active/inactive (like how to OC pins have an illumination underneath them? If so, or I can see on the UI anywhere what's happening, please screenie

Steve

**Comment by sjk7** [comment] 2023-04-29 09:53
UPDATE: Please try this, and feed back
https://github.com/sjk7/Thetis-2.9.0/releases/download/v2.9.0.4/Thetis-v2.9.0.x-TRYME-64.msi

**Comment by torrenthd** [comment] 2023-04-29 10:18
Just a quick test but seems fine to me!
Tnx!

**Comment by sjk7** [comment] 2023-04-29 10:19
> Just a quick test but seems fine to me! Tnx!

You are using the TRYME edition? lol ;-)

**Comment by torrenthd** [comment] 2023-04-29 10:20
> > Just a quick test but seems fine to me! Tnx!
> 
> You are using the TRYME edition? lol ;-)

Yes, tryme aka 3.0.9.26

**Comment by sjk7** [comment] 2023-04-29 10:26
ok, thanks, I will leave TRYME up for the other guys to test. Then we can move on from there.

Steve

**Comment by eu2av** [comment] 2023-04-29 10:47
Steve Thank you! I installed this version, now everything is working :)

**Comment by sjk7** [comment] 2023-04-29 11:08
Ok, looks like I have found it. Boy, this code is super-brittle and is in desperate need of refactoring internally.  I won't close this just yet to give others in different time zones an opportunity to feed back also.

Steve

**Comment by sjk7** [comment] 2023-04-29 11:09
> Steve Thank you! I installed this version, now everything is working :)

Thanks for your valuable feedback. Bugs like this, that only show up on certain ANAN models are tough for me as all I have here is an HL2.

**Comment by RdWing** [comment] 2023-04-29 11:46
Hi, I gave it a quick check here and all this one looks *squashed*, great work.

**Comment by w-u-2-o** [comment] 2023-04-29 13:09
Sorry to be late to the party. Running the "try me" version and all seems
well with this and the DUP issue.

ANAN-8000DLE, FW 2.1.18, Windows 10 Pro.

Thanks,

Scott

**Comment by oldjackbob** [comment] 2023-04-29 13:32
Steve, I'm the OP of #38, the TRYME version appears to have fixed the bug. Many thanks, sir!

If you still need a database mine is attached (let me know if it doesn't come through).

[Thetis_database_export_4-29-2023_8.29 AM.zip](https://github.com/sjk7/Thetis-2.9.0/files/11359281/Thetis_database_export_4-29-2023_8.29.AM.zip)

Mark

**Comment by oldjackbob** [comment] 2023-04-29 13:43
> Hi, I gave it a quick check here and this one looks _squashed_, great work. There is no explicit visual indication that this bypass is active, other than the proper PS levels, DUP display, and S-ATT value when TX'ing when using an amplifier.

The "Rx Bypass on TX" is simply a checkbox option in Setup > General > Ant/Filters > Antenna, you've either got it enabled or you don't. I don't see any need for an explicit visual indication in the Main Console that it's active. If you're not sure whether you've got it enabled then go look at the checkbox in Setup.

Mark

**Comment by kc9xg** [comment] 2023-04-29 14:47
ANAN 100D, P1, Rev16 PA/Filter board, Try me version  Ext1 working properly for PS.
![image](https://user-images.githubusercontent.com/18682554/235308850-0a4ef18a-2b10-43e9-8999-88868a3a9a19.png)

**Comment by kc9xg** [comment] 2023-04-29 15:13
ANAN 100D, P1, Rev16 PA/Filter board, Try me version.
Just tried on multiple bands.  No PS Two tone output on 12, 10 and 6 meters.  20, 15, 17 PS Two tone working as intended.

**Comment by oldjackbob** [comment] 2023-04-29 15:27
> ANAN 100D, P1, Rev16 PA/Filter board, Try me version. Just tried on multiple bands. No PS Two tone output on 12, 10 and 6 meters. 20, 15, 17 PS Two tone working as intended.

You should create a separate Bug Issue for that problem, this is not a catch-all bug report thread.

Mark

**Comment by w-u-2-o** [comment] 2023-04-29 15:31
Are you in CWL or CWU on the bands it does not work on?

I just tried to duplicate the problem here and found that two tone was not
working if the mode was CWL or CWU.

Will create a new issue.

ANAN-8000DLE, FW 2.1.18, Windows 10 Pro.

73,

Scott

**Comment by kc9xg** [comment] 2023-04-29 15:34
Scott,
  Yes, that was the issue with new install.  thanks.

**Comment by sjk7** [comment] 2023-04-29 17:26
> > Hi, I gave it a quick check here and this one looks _squashed_, great work. There is no explicit visual indication that this bypass is active, other than the proper PS levels, DUP display, and S-ATT value when TX'ing when using an amplifier.
> 
> The "Rx Bypass on TX" is simply a checkbox option in Setup > General > Ant/Filters > Antenna, you've either got it enabled or you don't. I don't see any need for an explicit visual indication in the Main Console that it's active. If you're not sure whether you've got it enabled then go look at the checkbox in Setup.
> 
> Mark

Not _quite_ that clear cut. The whole _tab_ does not exist for HL2 users like me!
Anyway, its solved, so closing.

**Closed by sjk7** 2023-04-29 17:26 UTC
Labels: bug, help wanted, good first issue, Good Feedback
