### ISSUE TITLE
Thetis-x64-2.9.0.18 does not save some settings

### ISSUE THREAD

**Issue by R6YY** [sjk7/Thetis-2.9.0#21] opened 2023-04-20 07:11 UTC
Hello Steve, First of all my great gratitude for your work. I admire your innovations.
I should note that in the latest versions of Thetis-x64-2.9.0... some parameter settings are not saved. When restarting, the values return to their original state. In particular, this applies to Buffer Size and Buffer Latency of VAC windows. Please help me.

![Thetis_not_save](https://user-images.githubusercontent.com/24804952/233287524-06d0d138-55c2-44ac-abc0-925f08317c19.jpg)

Win10pro x64, Dell I5-10500T, 32/256GB, Hermes by ApacheLabs.

**Comment by R6YY** [comment] 2023-04-20 08:02
Steve, thanks for the recommendations.
But it didn't help, alas.
P.S. I didn't touch the mod registers. So far, only DIGITAL mode.
PS 2. Increasing the buffer size greatly affects the delay of the audio signal via VAC.
I'll keep an eye on the topic. I wish you success.
Serge R6YY

**Comment by octatonicscale** [comment] 2023-04-20 09:58
Hi R6YY, Peter G7VKK here (Steve’s glamourous assistant!)

A table for you below about the TX Profile Preset Behaviour.

Not everything in each tab is saved to a profile – as the guys above have implied, you can reveal what is and what isn’t saved by ticking SETUP> TRANSMIT> ‘Highlight TX Profile Save Items’

Personally, I don’t use auto-save and I just go through each group, **set and manually save to a profile**. I sometimes export the database when happy just to be on the safe side! This prevents me inadvertently messing the settings up in the future! 

This Setup menu is confusing at the best of times - have a read through our comments, try them out and see if this works. 

I have just tried saving a Buffer Size, Sample Rate and Buffer Latency / RingBuffer / Port Audio settings and upon Thetis restart, they all saved successfully, but only for the selected mode group.

Let us know how you get on!

VY 73 DE Peter, G7VKK.

![image](https://user-images.githubusercontent.com/99284793/233330147-904bf540-dde8-4962-89f5-394fbe2c8207.png)

**Comment by sjk7** [comment] 2023-04-20 10:40
@BRUNO

Thanks for the documentation!

**Comment by R6YY** [comment] 2023-04-20 11:50
To G7VKK
Hello Peter, many thanks for your tips. When activating Auto Save TX Profile, the problem disappeared. While it's in DIGImode. But I will try all the modes and let you know the result additionally. Your and Steve's work is invaluable!
Success.
Serge R6YY

**Comment by octatonicscale** [comment] 2023-04-20 16:13
Many thanks Serge, glad we could help!

Will await any further comments before closing.

73.

Peter.

**Comment by R6YY** [comment] 2023-04-20 18:22
To DD8JM
Jorg, also thank you for your comment. I am always happy to read your news CQ-NRW. Good luck. 
Serge R6YY

**Comment by DD8JM** [comment] 2023-04-20 18:41
@R6YY
Thanks Serge, I'm glad you like my site. 

73 Joerg DD8JM

PS I had deleted my comment here, because everything was already clarified.

**Comment by sjk7** [comment] 2023-04-20 22:34
Thanks to all!

The sheer complexity of this software just trips people up all the time, including me!

Closing as not a bug,

Steve

**Closed** 2023-04-20 22:35 UTC
Labels: bug, documentation, good first issue, Not A Bug, Good Feedback
